---
# Install k3s with containerd configuration
- name: Create containerd config directory
  file:
    path: /etc/rancher/k3s
    state: directory
    mode: '0755'

- name: Create containerd config
  template:
    dest: /etc/rancher/k3s/config.yaml
    src: config.yaml.j2
    mode: '0644'

- name: Install k3s
  shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s

# Setup containerd permissions
- name: Create containerd group
  group:
    name: containerd
    state: present

- name: Add user to containerd group
  user:
    name: "{{ ansible_user }}"
    groups: containerd
    append: yes

- name: Create systemd override directory
  file:
    path: /etc/systemd/system/k3s.service.d
    state: directory
    mode: '0755'

- name: Create systemd override file
  template:
    dest: /etc/systemd/system/k3s.service.d/override.conf
    src: override.conf.j2
    mode: '0644'

# Setup Kubernetes configuration
- name: Ensure .kube directory exists
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Create symbolic link for kubectl config
  file:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/home/{{ ansible_user }}/.kube/config"
    state: link
    force: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
