---
- name: Create Kubernetes directory
  file:
    path: /home/{{ ansible_user }}/k3s/{{ app_name }}
    state: directory

- name: Install cert manager
  shell: |
    kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.1/cert-manager.yaml
  become: yes
  become_user: "{{ ansible_user }}"

- name: Create cert issuer for letsencrypt
  template:
    src: cert-issuer.yml.j2
    dest: /home/{{ ansible_user }}/k3s/{{ app_name }}/cert-issuer.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create Kubernetes namespace file
  template:
    src: namespace.yml.j2
    dest: /home/{{ ansible_user }}/k3s/{{ app_name }}/namespace.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create Kubernetes deployment file
  template:
    src: deployment.yml.j2
    dest: /home/{{ ansible_user }}/k3s/{{ app_name }}/deployment.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create Kubernetes service file
  template:
    src: service.yml.j2
    dest: /home/{{ ansible_user }}/k3s/{{ app_name }}/service.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create Kubernetes Ingress file
  template:
      src: ingress.yml.j2
      dest: "/home/{{ ansible_user }}/k3s/{{ app_name }}/ingress.yml"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0644'

- name: Remove namespace if it exists
  kubernetes.core.k8s:
    state: absent
    src: "/home/{{ ansible_user }}/k3s/{{ app_name }}/namespace.yml"
  ignore_errors: yes
  become: yes
  become_user: "{{ ansible_user }}"

- name: Wait for namespace deletion to complete
  kubernetes.core.k8s_info:
    kind: Namespace
    name: "{{ app_namespace }}"
  register: namespace_check
  until: namespace_check.failed or namespace_check.resources | length == 0
  retries: 30
  delay: 10
  ignore_errors: yes
  become: yes
  become_user: "{{ ansible_user }}"

- name: Apply Kubernetes namespace
  kubernetes.core.k8s:
    state: present
    src: "/home/{{ ansible_user }}/k3s/{{ app_name }}/namespace.yml"
  become: yes
  become_user: "{{ ansible_user }}"

- name: Apply cert issuer
  kubernetes.core.k8s:
    state: present
    src: "/home/{{ ansible_user }}/k3s/{{ app_name }}/cert-issuer.yml"
  become: yes
  become_user: "{{ ansible_user }}"

- name: Apply Kubernetes deployment
  kubernetes.core.k8s:
    state: present
    src: "/home/{{ ansible_user }}/k3s/{{ app_name }}/deployment.yml"
  become: yes
  become_user: "{{ ansible_user }}"

- name: Apply Kubernetes service
  kubernetes.core.k8s:
    state: present
    src: "/home/{{ ansible_user }}/k3s/{{ app_name }}/service.yml"
  become: yes
  become_user: "{{ ansible_user }}"

- name: Apply Kubernetes Ingress
  kubernetes.core.k8s:
    state: present
    src: "/home/{{ ansible_user }}/k3s/{{ app_name }}/ingress.yml"
  become: yes
  become_user: "{{ ansible_user }}"
