---
- name: Create n8n directory
  file:
    path: /home/{{ ansible_user }}/k3s/n8n/
    state: directory

- name: Create n8n namespace file
  template:
    src: n8n_namespace.yml.j2
    dest: /home/{{ ansible_user }}/k3s/n8n/namespace.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create Kubernetes secret for Postgres password
  template:
    src: n8n_postgres_secret.yml.j2
    dest: /home/{{ ansible_user }}/k3s/n8n/postgres_secret.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"  
