---
- name: Update apt cache
  apt:
    update_cache: yes

#
# kubernetes stuff
#
- name: Install kubernetes module dependencies
  apt:
    name:
      - python3-pip
      - python3-setuptools
    state: present

- name: Install kubernetes Python package with pip
  pip:
    name: kubernetes>=24.2.0
    state: present

#
# azure stuff
#
- name: Install azure-core Python package
  pip:
    name: 
      - azure-core
      - azure-common
      - azure-identity
      - azure-keyvault-secrets
      - azure-mgmt-keyvault
    state: latest
    extra_args: --upgrade --force-reinstall
  become: true
