---
- hosts: all
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install k3s
      shell: curl -sfL https://get.k3s.io | sh -

    - name: install git
      apt:
        name: git
        state: present

    - name: Clone git repo
      git:
        repo: "{{ git_repo_url }}"
        dest: /home/adminuser/apps/{{ app_name }}
        version: HEAD
        force: yes
      become: yes
      become_user: adminuser